//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginFormUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Codeword { get; set; }
        public string SecretQuestionAnswer { get; set; }
        public int CodeSecretQuestionId { get; set; }
        public int UserId { get; set; }
    
        public virtual SecretQuestion SecretQuestion { get; set; }
    }
}
